markdown: kramdown
permalink: /blog/:year/:month/:day/:title
pages_dir: /pages
high_res_image: "/assets/images/Alexander_cuts_the_Gordian_Knot.221k.75.webp"
low_res_image: "/assets/images/Alexander_cuts_the_Gordian_Knot.28k.0.webp"
default_image: "/assets/images/Alexander_cuts_the_Gordian_Knot.221k.75.webp"
url: "https://diogenesanalytics.com"
contacts:
  business: "/contact/"
social:
  youtube: "https://www.youtube.com/@DiogenesAnalytics"
exclude:
  - CNAME
  - Dockerfile
  - Makefile
  - README.md
  - tests
